inputdir: "/fast/users/altwassr_c/scratch/P1519/demux/mapped"
workdir: "/fast/users/altwassr_c/scratch/P1519/variantcalling/"
snakedir: "/fast/users/altwassr_c/work/umi-testing/umi-variantcalling/"
bedfile: "/fast/users/altwassr_c/work/refs/merged_probe_file_DKMS_v5-hrd_1X_1p5X_hg38.bed"
refgenome: "/fast/users/altwassr_c/work/refs/GRCh38.u2af1_fix.v1.2020_04_01.fa"

#### ABSOLUTE PATHS ############
paths:
  mystatic: /fast/groups/ag_damm/work/ref/
  bihstatic: /fast/projects/cubit/current/static_data
  scripts: scripts/ # folder relative to snakedir

#### TOOLS SECTION ##############
tools:
  annovar: perl /fast/users/altwassr_c/work/programme/annovar
mpileup:
  Q: 20   # base quality
  MAPQ: 10 # -q in pileup
annovar:
  build: hg38
  path_to_humandb: /fast/users/altwassr_c/work/programme/annovar/humandb
  annofiles:
    - refGene
    - cytoBand
    - clinvar_20200316
    - dbnsfp35c
    - gnomad30_genome
    - avsnp150
    - cosmic92_coding
    - cosmic92_noncoding
    - revel
    - nci60
edit:
  extended_output: False
  candidate_list: /fast/users/altwassr_c/work/umi-data-processing/umi-variantcalling/info/AML_candidates.txt
  driver_list: /fast/users/altwassr_c/work/umi-data-processing/umi-variantcalling/info/AML_drivers.txt
  CHIP_list: /fast/users/altwassr_c/work/umi-data-processing/umi-variantcalling/info/CHIP_mut.txt
  normals: /fast/users/altwassr_c/work/umi-data-processing/umi-variantcalling/ref/normal_bam_aml.txt
filter_bam:
    threads: 4
    stringency_for_IGVnav: moderate
    padding: 200
    folder: filterbam
primer3:  # is applied after filter step 1
  threads: 10
  min_size: 120
  max_size: 220
  center_offSet: 5 # how much offSet primer pairs can
  use_primer_list: ''
  split: "/data/gpfs-1/users/altwassr_c/work/refs/split_hg38_u2af1_fix"
HDR:
  threads: 2
  min_HDR_count: 1 # minimum lanes around mutation to make it a putative HDR
  min_similarity: .85 # which similarities to consider as HDR
  padding: 150  # range around mutation to be scanned
  min_q: 20 # minimum base quality to be used for HDR-calculation
